export TESTING_USER=${TESTING_USER:-pjpg_test}
export TESTING_PASSWORD=${TESTING_PASSWORD:-pjpg_test}
export TESTING_DATABASE=${TESTING_DATABASE:-pjpg_test}
export TESTING_HOST=${TESTING_HOST:-localhost}
export TESTING_PORT=${TESTING_PORT:-5432}
